export const SETMODEL = "SETMODEL";
export const UPDATE_MODEL_INDEX = "UPDATE_MODEL_INDEX";
export const SET_DETECTION_MODEL = "SET_DETECTION_MODEL";
export const DELETE_MODEL_INDEX = "DELETE_MODEL_INDEX";
export const SET_TICKETS_DATA = "SET_TICKETS_DATA";
